---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: fireboard
  scrape_interval: 30s
  honor_labels: true
  static_configs:
    - targets:
      - fireboard-exporter:8080
